# Generated by Django 4.2.4 on 2023-09-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='duration_extended',
            field=models.IntegerField(default=0),
        ),
    ]
