# Generated by Django 4.2 on 2023-06-02 23:40

import activity.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("activity_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=20)),
                ("kind", models.CharField(max_length=20)),
                ("people_number", models.CharField(max_length=3)),
                ("talent", models.TextField()),
                ("frequency", models.TextField()),
                ("way", models.TextField()),
                ("period", models.CharField(max_length=3)),
                ("recruit", models.BooleanField(default=True)),
                ("payment", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                ("board_id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=30)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=activity.models.Board.get_upload_path_logo,
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=activity.models.Board.get_upload_path_banner,
                    ),
                ),
                ("introduction", models.TextField()),
                ("vision", models.TextField()),
                ("pride", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=150)),
                ("duration", models.DurationField()),
                ("is_expired", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                ("form_id", models.AutoField(primary_key=True, serialize=False)),
                ("word", models.TimeField()),
                ("is_accepted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Scrap",
            fields=[
                ("scrap_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "board_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="activity.board"
                    ),
                ),
            ],
        ),
    ]
