# Generated by Django 4.2.3 on 2023-07-11 04:44

import activity.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("kind", models.CharField(max_length=20)),
                ("people_number", models.IntegerField()),
                ("talent", models.TextField()),
                ("frequency", models.TextField()),
                ("way", models.TextField()),
                ("period", models.DurationField()),
                ("recruit", models.BooleanField(default=False)),
                ("payment", models.CharField(default="없음", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=activity.models.Board.get_upload_path_logo,
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=activity.models.Board.get_upload_path_banner,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=30, null=True)),
                ("company_name", models.CharField(max_length=30)),
                ("introduction", models.TextField()),
                ("vision", models.TextField()),
                ("pride", models.CharField(blank=True, max_length=300, null=True)),
                ("address", models.CharField(max_length=150)),
                ("duration", models.DurationField()),
                ("is_expired", models.BooleanField(default=False)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("introduce", models.TextField()),
                ("reason", models.TextField()),
                ("merit", models.TextField()),
                (
                    "accept_status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("waiting", "확정대기"),
                            ("canceled", "활동취소"),
                            ("rejected", "불합격"),
                            ("accepted", "합격"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Scrap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrap",
                        to="activity.board",
                    ),
                ),
            ],
        ),
    ]
