# Generated by Django 4.2.4 on 2023-08-30 22:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
        ("activity", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="scrap",
            unique_together={("board", "student_user")},
        ),
    ]
