# Generated by Django 4.2.3 on 2023-07-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="duration_extended",
            field=models.IntegerField(default=0),
        ),
    ]
