# Generated by Django 4.2.4 on 2023-09-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('activity', '0003_alter_scrap_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='form',
            unique_together={('student_user', 'activity')},
        ),
    ]
