# Generated by Django 4.2.3 on 2023-07-25 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_user_options_user_is_company_user"),
        ("activity", "0003_board_duration_extended"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form",
                to="activity.activity",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="student_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form",
                to="user.studentuser",
            ),
        ),
    ]
