# Generated by Django 4.2.3 on 2023-07-27 23:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0004_alter_form_activity_alter_form_student_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="is_expired",
        ),
    ]
