# Generated by Django 4.2 on 2023-06-15 07:50

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activity", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "username",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "기본유저모델",
            },
        ),
        migrations.CreateModel(
            name="PortfolioFiles",
            fields=[
                (
                    "portfolio_files_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudentUser",
            fields=[
                (
                    "student_user_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "activity_id",
                    models.ManyToManyField(
                        through="activity.Form", to="activity.activity"
                    ),
                ),
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "학생유저",
            },
        ),
        migrations.CreateModel(
            name="StudentUserProfile",
            fields=[
                (
                    "student_user_profile_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=10)),
                (
                    "portfolio_image",
                    models.ImageField(
                        upload_to=user.models.StudentUserProfile.get_upload_path
                    ),
                ),
                ("birth", models.DateField()),
                ("phone_number", models.CharField(max_length=20)),
                ("university", models.CharField(max_length=10)),
                ("major", models.CharField(max_length=20)),
                ("univ_email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.studentuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentUserPortfolio",
            fields=[
                (
                    "student_user_portfolio_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=20)),
                ("contents", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.studentuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioOneFile",
            fields=[
                (
                    "portfolio_one_file_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=user.models.PortfolioOneFile.get_upload_path,
                    ),
                ),
                (
                    "portfolio_files_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.portfoliofiles",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="portfoliofiles",
            name="student_user_portfolio_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.studentuserportfolio",
            ),
        ),
        migrations.CreateModel(
            name="CompanyUser",
            fields=[
                (
                    "company_user_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("business_number", models.CharField(max_length=10)),
                ("ceo_name", models.CharField(max_length=10)),
                ("start_date", models.DateField()),
                ("manager_phone", models.CharField(max_length=20)),
                ("manager_email", models.EmailField(max_length=254)),
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "기업유저",
            },
        ),
    ]
