# Generated by Django 4.2 on 2023-07-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyuser',
            options={'verbose_name': 'CompanyUser'},
        ),
        migrations.AlterModelOptions(
            name='studentuser',
            options={'verbose_name': 'StudentUser'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'BaseUserModel'},
        ),
    ]
