# Generated by Django 4.2.3 on 2023-07-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_companyuser_user_alter_studentuser_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyuser",
            name="business_number",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="companyuser",
            name="corporate_number",
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name="companyuser",
            name="manager_email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="companyuser",
            name="manager_phone",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
