# Generated by Django 4.2.3 on 2023-07-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_companyuser_business_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User"},
        ),
        migrations.AddField(
            model_name="user",
            name="is_company_user",
            field=models.BooleanField(default=False),
        ),
    ]
