from django.urls import path
from .views import (
    BoardListView,
    BoardDetailView,
    BoardCreateView,
    BoardDurationExtendView,
    CompanyUserBoardListView,
    CompanyUserBoardDetailView,
    ScrapListView,
    ScrapDetailView,
    ScrapCreateView,
    ScrapDeleteView,
    FormListView,
    FormDetailView,
    FormCreateView,
)

urlpatterns = [
    path(
        "boards/",
        BoardListView.as_view(),
        name="board-list",
    ),
    path(
        "board/<int:pk>/",
        BoardDetailView.as_view(),
        name="board-detail",
    ),
    path(
        "board/create/",
        BoardCreateView.as_view(),
        name="board-create",
    ),
    path(
        "board/<int:pk>/extend/",
        BoardDurationExtendView.as_view(),
        name="board_duration-extend",
    ),
    path(
        "boards/company/",
        CompanyUserBoardListView.as_view(),
        name="board-list-company",
    ),
    path(
        "board/company/<int:pk>/",
        CompanyUserBoardDetailView.as_view(),
        name="board-detail-company",
    ),
    path(
        "scraps/",
        ScrapListView.as_view(),
        name="scrap-list-board",
    ),
    path(
        "scrap/<int:pk>/",
        ScrapDetailView.as_view(),
        name="scrap-detail-board",
    ),
    path(
        "scrap/create/",
        ScrapCreateView.as_view(),
        name="scrap-create",
    ),
    path(
        "scrap/delete/<int:board_pk>/",
        ScrapDeleteView.as_view(),
        name="scrap-delete",
    ),
    path(
        "form/create/",
        FormCreateView.as_view(),
        name="form-create",
    ),
]
